export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const PUT_NAME = 'PUT_NAME';
export const PUT_NAME_SUCCESS = 'PUT_NAME_SUCCESS';
export const PUT_NAME_FAILED = 'PUT_NAME_FAILED';

export const PUT_IMAGE = 'PUT_IMAGE';
export const PUT_IMAGE_SUCCESS = 'PUT_IMAGE_SUCCESS';
export const PUT_IMAGE_FAILED = 'PUT_IMAGE_FAILED';

export const DELETE_IMAGE = 'DELETE_IMAGE';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAILED = 'DELETE_IMAGE_FAILED';

export const PUT_OVERVIEW = 'PUT_OVERVIEW';
export const PUT_OVERVIEW_SUCCESS = 'PUT_OVERVIEW_SUCCESS';
export const PUT_OVERVIEW_FAILED = 'PUT_OVERVIEW_FAILED';

export const PUT_NUMBER = 'PUT_NUMBER';
export const PUT_NUMBER_SUCCESS = 'PUT_NUMBER_SUCCESS';
export const PUT_NUMBER_FAILED = 'PUT_NUMBER_FAILED';

export const SENT_OFFER = 'SENT_OFFER';
export const SENT_OFFER_SUCCESS = 'SENT_OFFER_SUCCESS';
export const SENT_OFFER_FAILED = 'SENT_OFFER_FAILED';

export const SET_LOADING = 'SET_LOADING';

export const SET_USER = 'SET_USER';
export const SET_USER_FAILED = 'SET_USER_FAILED';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';
export const DELETE_USER = 'DELETE_USER';
